# Generated by Django 6.0.3 on 2026-04-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_failure_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='failed_at',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
