# Generated by Django 6.0.3 on 2026-04-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
    ]
