# Generated by Django 6.0.3 on 2026-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discipline_score',
            field=models.FloatField(default=0.0),
        ),
    ]
