# Generated by Django 6.0.3 on 2026-04-08 17:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_discipline_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline_time',
        ),
        migrations.AddField(
            model_name='task',
            name='consequence_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='days_of_week',
            field=models.JSONField(default=core.models.default_days_of_week),
        ),
    ]
