# Generated by Django 6.0.4 on 2026-04-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_task_options_remove_task_deadline_time_and_more'),
    ]

    operations = [
    ]
